Update configure script to include git-core as a build dep

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -275,7 +275,7 @@ fi
 # Install dependencies for building the kernel
 apt-get build-dep linux --no-install-recommends -y || die "Error installing \"build-dep linux\""
 
-apt-get install kernel-package bin86 devscripts binutils-dev crash libncurses5-dev libnuma-dev libperl-dev makedumpfile libelf-dev python-six initramfs-tools --no-install-recommends -y || die "Error installing build dependencies"
+apt-get install kernel-package bin86 devscripts binutils-dev crash libncurses5-dev libnuma-dev libperl-dev makedumpfile libelf-dev python-six initramfs-tools git-core --no-install-recommends -y || die "Error installing build dependencies"
 
 # Get the linux source
 if [ "x$linuxnext_opt" = "xyes" ]; then
